# Site settings
title: Rhino.Inside.Revit Documentation
# email: brian@mcneel.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
editme_github_base_url: "mcneel/rhino.inside-revit"
description: Rhino.Inside.Revit Documentation
copyright: Robert McNeel & Associates

gems:
  - jekyll-sitemap

github_username:  mcneel
simple_search: http://google.com/search

# Build settings
encoding: utf-8

# If we decide that we want to use kramdown over redcarpet, syntax
# highlighting is performed by turning on the following options and
# including/running highlight.js (https://highlightjs.org/) at the
# top of pages that need it (probably just add to head.html)
#markdown: redcarpet
markdown: kramdown
kramdown:
  input: GFM

safe: false

collections:
  en:
    output: true
    permalink: /en/:path

defaults:
  - scope:
      path: ""
      type: en
    values:
      language: en
